version: '2'

services:
    web:
        build:
            context: .
        links:
            - db
        volumes:
            - "${PWD}:/mem_words"
        ports:
            - "51888:8000"
        networks:
            - dev-network
        environment:
            dbname: postgres
            user: postgres
            host: db
            port: 5432

        depends_on:
            - "db"
        command: ["python", "server.py"]

    db:
        image: "postgres:9.6"
        networks:
            - dev-network

    redis:
        image: "redis"
        networks:
            - dev-network
networks:
    dev-network:
        driver: bridge
